---
title: "Dashboard"
format: dashboard
server: shiny
---

```{r}
#| context: setup
library(ggplot2)
library(shiny)
dataset <- diamonds
```


```{r}

dateRangeInput(inputId = "date_lim",
               label = "Date range for plots",
               min   = "2022-08-01",
               start = "2023-08-01",
               end   = "2023-09-01"
)

selectInput( inputId = "phase_type",
             label = "Phase Type",
             selected = "Cutting",
             choices = c("Bulking",
                         "Cutting" 
             )
)

conditionalPanel(condition = "input.phase_type == 'Bulking'",
                 
                 numericInput(inputId = "bulk_val",
                              label = "Bulking target, BM in kg/week",
                              value = "0.5",
                              step = 0.1,
                              min = 0,
                 ),
                 # tabItem("about",
                 #         h1("Note: gaining 500g/week of body mass should be the maximum value,
                 #                          with a 50% gain ratio of lean mass and 50% fat mass (250g/week for each).
                 #                          This totals for 1.8kg/month of body mass.")),
                 
                 # helpText("Note: gaining 500g/week of body mass should be the maximum value,
                 #                          with a 50% gain ratio of lean mass and 50% fat mass (250g/week for each).
                 #                          This totals for 1.8kg/month of body mass.")
)

conditionalPanel(condition = "input.phase_type == 'Cutting'",
                 
                 numericInput(inputId = "cut_val",
                              label = "Cutting target, BM in kg/week",
                              value = "0.7",
                              step = 0.1,
                              min = 0,
                 ),
                 
                 # p("Note: loosing 700g/week should be the maximum value,
                 #                          with a 70% loss ratio of fat mass and 30% lean mass (500g/week of fat mass and 250g of lean mass).
                 #                          This totals for 3kg/month of body mass"),
)


```


```{r}
plot(mtcars)
```